OBJS := fat32_super_operations.o fat32_inode_operations.o fat32_address_space_operations.o \
		fat32_file_operations.o fat32_dentry_operations.o fat32_utils.o fat32_init.o

include $(SUB_MAKE_INCLUDE)